name: lamps3
description: A new Flutter application.

version: 1.0.8+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.2
  google_sign_in: ^4.2.0
  rxdart: ^0.23.1
  cloud_firestore: 0.13.4+2
  cloud_functions: 0.4.2+3
  package_info: 0.4.0+16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
