name: lamps3
description: A new Flutter application.

version: 1.13.3+9

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.2
  google_sign_in: ^4.2.0
  rxdart: ^0.23.1
  cloud_firestore: 0.13.4+2
  cloud_functions: 0.4.2+3
  package_info: 0.4.0+16
  google_fonts: ^0.4.0
  vibration: 1.2.4
  flutter_launcher_icons: 0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
